-- Keycloak
CREATE USER keycloak WITH ENCRYPTED PASSWORD '${KEYCLOAK_DB_PASSWORD}';
CREATE DATABASE keycloak OWNER keycloak;

-- Your API
CREATE USER app WITH ENCRYPTED PASSWORD 'app';
CREATE DATABASE appdb OWNER app;
GRANT ALL PRIVILEGES ON DATABASE appdb TO app;
