GRANT ALL PRIVILEGES ON DATABASE audit TO keycloak;
GRANT USAGE, CREATE ON SCHEMA public TO keycloak;
GRANT USAGE ON SCHEMA audit TO keycloak;
GRANT USAGE ON SCHEMA policy TO keycloak;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO keycloak;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO keycloak;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO keycloak;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO keycloak;
